#!/bin/sh
### BEGIN INIT INFO
# Required-Start: $local_fs $remote_fs $network $syslog $network $inetd
# Required-Stop: $local_fs $remote_fs $network $syslog $network $inetd
# Default-Start: 3 4 5
# Default-Stop: 0 1 6
# X-Interactive: true
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/bin:/usr/sbin
NAME=STGI-upstart
DESC="Resolution du upstart qui ne fonctionne pas"

test -f $DAEMON || exit 1

. /lib/lsb/init-functions

case "$1" in
        start)

                service portmap start
                service rpcbind start
                service nfs-kernel-server start
                service nmbd start
                service smbd start
                log_begin_msg "Starting $DESC: $NAME"
                ;;
        stop)

                service portmap stop
                service rpcbind stop
                service nfs-kernel-server stop
                service nmbd stop
                service smbd stop
                ;;
        *)
                echo "Usage STGI-upstart {start|stop}" >&2
                exit 1;
                ;;
esac

exit 0;
